flowchart TD
  subgraph batter["Batter"]
    direction TB
    swing{Swing?}
    swing --> |No|take_pitch
    swing --> |Yes & Miss|swing_miss
    swing --> |Yes & Hit|calculate_batted_ball
  end

  subgraph calculate_batted_ball
    direction TB
    sample_spray_angle --> inner_choose_sector --> get_angle_range
  end

  calculate_batted_ball --> process_fielding
  calculate_batted_ball --> |homerun|after_homerun
  calculate_batted_ball --> |ground_rule_double|after_ground_rule_double

  subgraph process_fielding
    is_ball_in_fielder_lane --> evaluate_fielder_interception
    evaluate_fielder_interception --> evaluate_final_pickup
  end

  process_fielding --> evaluate_defense_play


  subgraph evaluate_defense_play["evaluate defense play"]
    infield{Infield?} --> |YES & Grounder|judge_infield_grounder_throw_target

    judge_infield_grounder_throw_target --> infield_grounder_defense_play

    infield --> |NO & Grounder|judge_outfield_hit_throw_target
    infield --> |NO & Fly & TagUp|judge_tagup_throw_target

    judge_tagup_throw_target --> outfield_hit_tagup_defense_play
    judge_outfield_hit_throw_target --> outfield_hit_tagup_defense_play
  end

  infield_grounder_defense_play --> fielder3

  subgraph fielder3["Fielder3"]
    evaluate_double_play
  end

  subgraph evaluate_double_play["evaluate double play"]
    judge_double_play_throw_target --> double_play_defense_play
  end

  outfield_hit_tagup_defense_play --> after_outfield_hit
  outfield_hit_tagup_defense_play --> after_tagup
  infield_grounder_defense_play --> after_infield_grounder
  double_play_defense_play --> after_double_play
  evaluate_base_stealing --> after_base_stealing

  subgraph runner
    after_homerun
    after_ground_rule_double

    after_infield_grounder --> commit_unsaved_runners
    after_outfield_hit --> commit_unsaved_runners
    after_tagup --> commit_unsaved_runners
    after_base_stealing
    after_double_play --> commit_unsaved_runners
  end




