flowchart TD
    calculate_zone_similarity_factor --> calculate_swing_factor
    calculate_zone_similarity_factor --> |Swing|adapt_to_pitch
    calculate_pitch_similarity --> calculate_swing_factor
    calculate_pitch_similarity --> |Swing|adapt_to_pitch
    calculate_swing_factor --> select_swing_execution
    select_swing_execution --> |Swing|adapt_to_pitch --> evaluate_swing_contact
    select_swing_execution --> |Swing|calculate_swing_execution_error --> evaluate_swing_contact
    evaluate_swing_contact --> calculate_batted_ball

    subgraph calculate_swing_execution_error
        direction TB
        calculate_bat_angle --> calculate_dynamic_attack_angle
    end

    subgraph calculate_batted_ball
        direction TB
        classify_trajectory_type
        calculate_collision_spin --> combine_batted_spin --> calculate_3d_flight_path
        calculate_effective_c_swing --> calculate_launch_speed_with_power --> calculate_3d_flight_path
        calculate_launch_angles --> calculate_3d_flight_path
    end
