flowchart TD
    subgraph pitcher
        base_spin_angle
        select_pitch_skill
        sample_pitch_calling
        calculate_release_point
        calculate_flight_time
        sample_ball_location
    end

    subgraph create_pitch
        pitcher
        calculate_flight_time
    end

    subgraph MatchupContext
        crossfire_perceived_multiplier
    end

    calculate_hanging_pitch_effect --> create_pitch 
    create_pitch --> MatchupContext --> calculate_pitch_offset
    create_pitch --> calculate_location_bias --> calculate_pitch_offset
    create_pitch --> calculate_ball_movement

    subgraph calculate_pitch_offset
        get_side_accel
        get_vertical_accel
        calculate_timing_offset
    end