[package]
name = "statbb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
directories = "6.0"
rand = { version = "0.10.1", features = ["std"] }
rand_distr = "0.6.0"
rusqlite = { version = "0.39.0", features = ["bundled", "chrono"] }
deadpool = "0.12.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_rusqlite = "0.42.0"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28"
clap = { version = "4.6.1", features = ["derive"] }
chrono = { version = "0.4.44", features = ["serde"] }
inquire = "0.9.4"
fluent-templates = "0.14.0"
unic-langid = "0.9"
confy = "2.0.0"
console = "0.16.3"
dialoguer = "0.12.0"
comfy-table = "7.2.2"
crossterm = "0.29.0"
futures = "0.3"