DROP TABLE test_batted_ball;

CREATE TABLE test_batted_ball (
    horizontal_offset_m REAL NOT NULL,
    vertical_offset_m REAL NOT NULL,
    timing_offset_sec REAL NOT NULL,
    swing_factor REAL NOT NULL,
    swing_execution TEXT NOT NULL,
    adapted_x_m REAL NOT NULL,
    adapted_z_m REAL NOT NULL,
    adapted_timing REAL NOT NULL,
    additional_x_m REAL NOT NULL,
    additional_z_m REAL NOT NULL,
    ideal_bat_angle_deg REAL NOT NULL,
    actual_bat_angle_deg REAL NOT NULL,
    ideal_attack_angle_deg REAL NOT NULL,
    actual_attack_angle_deg REAL NOT NULL,
    timing_impact_x_m REAL NOT NULL,
    offset_x_m REAL NOT NULL,
    offset_z_m REAL NOT NULL,
    thickness_offset_m REAL NOT NULL,
    length_offset_m REAL NOT NULL,
    contact_type TEXT NOT NULL,
    modified_attack_angle_deg REAL NOT NULL,
    launch_speed_ms REAL NOT NULL,
    launch_angle REAL NOT NULL,
    spray_angle REAL NOT NULL,
    distance_m REAL NOT NULL,
    hang_time_sec REAL NOT NULL,
    trajectory TEXT NOT NULL
);