DROP TABLE test_pitched_ball;

CREATE TABLE test_pitched_ball (
    pitch_type TEXT NOT NULL,
    expected_pitch_type TEXT NOT NULL,
    speed_ms REAL NOT NULL,
    spin_rate REAL NOT NULL,
    spin_angle REAL NOT NULL,
    spin_efficiency REAL NOT NULL,
    release_point_x REAL NOT NULL,
    release_point_y REAL NOT NULL,
    release_point_z REAL NOT NULL,
    flight_time REAL NOT NULL,
    aim_zone TEXT NOT NULL,
    aim_x REAL NOT NULL,
    aim_y REAL NOT NULL,
    actual_x REAL NOT NULL,
    actual_y REAL NOT NULL,
    pitch_result TEXT NOT NULL,
    movement_x REAL NOT NULL,
    movement_z REAL NOT NULL,
    location_bias_x REAL NOT NULL,
    location_bias_y REAL NOT NULL,
    location_bias_timing REAL NOT NULL,
    crossfire_multiplier REAL NOT NULL,
    release_x_factor REAL NOT NULL,
    disp_x REAL NOT NULL,
    disp_y REAL NOT NULL,
    timing REAL NOT NULL
);