flowchart TD
  subgraph pitcher["Pitcher"]
    pitch_ball
  end

  pitch_ball --> batter
    
  subgraph batter["Batter"]
    direction TB
    swing{Swing?}
    swing --> |No|take_pitch
    swing --> |Yes and Miss|swing_miss
    swing --> |Yes and Hit|calculate_batted_ball
  end

  subgraph calculate_batted_ball["Calculate Batted Ball"]
    direction TB
    sample_spray_angle --> inner_choose_sector --> get_angle_range
  end

  calculate_batted_ball --> process_defensive_chain

  subgraph process_defensive_chain["Process Defensive Chain"]
    is_ball_in_fielder_lane --> calculate_height_at_distance1["calculate height at distance"]
    calculate_height_at_distance1 --> find_closest_fielder
  end

  process_defensive_chain --> fielder1

  subgraph fielder1["Fielder1"]
    direction TB
    try_catch
  end

  subgraph try_catch["Try Catch"]
    direction TB
    outfield{Ball is Outfield?} --> |YES|over_the_fence{Over the Fence?}
    over_the_fence --> |YES and Fly or Liner|calculate_height_at_distance2{"calculate height at distance"}
    calculate_height_at_distance2 --> |higher than fence|HOMERUN!
    calculate_height_at_distance2 --> |lower than fence|process_bounded_ball
    over_the_fence --> |YES and Grounder|process_bounded_ball
    over_the_fence --> |NO and Fly or Liner|catch_fly1{Catch Fly?}
    outfield{Ball is Outfield?} --> |NO and Fly or Liner|catch_fly1{Catch Fly?}
    catch_fly1 --> |YES|OUT!
    catch_fly1 --> |NO|process_bounded_ball
    catch_fly1 --> |NO|process_bounded_ball
  end

  process_bounded_ball --> fielder2
    outfield{Ball is Outfield?} --> |NO and Grounder|fielder2

  subgraph fielder2["Fielder2 + Cut Off Man"]
    evaluate_defense_play --> evaluate_double_play
    evaluate_base_stealing
  end

  subgraph evaluate_defense_play["evaluate defense play"]
    infield{Infield Play?} --> |YES|judge_infield_grounder_throw_target
    judge_infield_grounder_throw_target --> infield_grounder_defense_play

    infield{Infield Play?} --> |NO|catch_fly2
    catch_fly2{Catch Fly?} --> |YES|judge_tagup_throw_target
    catch_fly2{Catch Fly?} --> |NO|judge_outfield_hit_throw_target

    judge_tagup_throw_target --> outfield_defense_play
    judge_outfield_hit_throw_target --> outfield_defense_play
  end

  subgraph evaluate_double_play["evaluate double play"]
    judge_double_play_throw_target --> double_play_defense_play
  end

  outfield_defense_play --> after_outfield_hit
  outfield_defense_play --> after_tagup
  infield_grounder_defense_play --> after_double_play
  double_play_defense_play --> after_double_play
  evaluate_base_stealing --> after_base_stealing

  subgraph runner
    after_homerun
    after_infield_grounder --> commit_unsaved_runners
    after_outfield_hit --> commit_unsaved_runners
    after_tagup --> commit_unsaved_runners
    after_base_stealing
    after_double_play --> commit_unsaved_runners
  end




