flowchart TD
  subgraph pitcher["Pitcher"]
    pitch_ball
  end

  pitch_ball --> batter
    
  subgraph batter["Batter"]
    direction TB
    swing{Swing?}
    swing --> |No|take_pitch
    swing --> |Yes and Miss|swing_miss
    swing --> |Yes and Hit|calculate_batted_ball
  end

  subgraph calculate_batted_ball["Calculate Batted Ball"]
    direction TB
    sample_spray_angle --> inner_choose_sector --> get_angle_range
  end

  calculate_batted_ball --> process_defensive_chain
  calculate_batted_ball --> runner

  subgraph process_defensive_chain["Process Defensive Chain"]
    is_ball_in_fielder_lane --> calculate_height_at_distance1["calculate height at distance"]
    calculate_height_at_distance1 --> find_closest_fielder
  end

  process_defensive_chain --> fielder1

  subgraph fielder1["Fielder1"]
    direction TB
    try_catch
  end

  subgraph try_catch["Try Catch"]
    direction TB
    outfield{Ball is Outfield?} --> |YES|over_the_fence{Over the Fence?}
    over_the_fence --> |YES and Fly or Liner|calculate_height_at_distance2{"calculate height at distance"}
    calculate_height_at_distance2 --> |higher than fence|HOMERUN!
    calculate_height_at_distance2 --> |lower than fence|process_bounded_ball
    over_the_fence --> |YES and Grounder|process_bounded_ball
    over_the_fence --> |NO and Fly or Liner|catch_fly{Catch?}
    outfield{Ball is Outfield?} --> |NO and Fly or Liner|catch_fly{Catch?}
    catch_fly --> |YES|OUT!
    catch_fly --> |NO|process_bounded_ball
    catch_fly --> |NO|process_bounded_ball
  end

  process_bounded_ball --> fielder2
    outfield{Ball is Outfield?} --> |NO and Grounder|fielder2

  subgraph fielder2["Fielder2 + Cut Off Man"]
    evaluate_defense_play
  end

  subgraph evaluate_defense_play["evaluate defense play"]
    evaluate_tagup_play
    evaluate_outfield_hit_play
    evaluate_grounder_play
  end

  subgraph evaluate_tagup_play["evaluate tagup play"]
    judge_optimal_target_general1["judge optimal target general"] --> cutt_off1{Cut Off?}
    cutt_off1 --> |YES|calculate_relay_play_time1["calculate relay play time"]
    calculate_relay_play_time1 --> calculate_ball_flight_time1["calculate ball flight time"]
    cutt_off1 --> |NO|calculate_ball_flight_time1
  end

  subgraph evaluate_outfield_hit_play["evaluate outfield hit play"]
    judge_optimal_target_general2["judge optimal target general"] --> cutt_off2{Cut Off?}
    cutt_off2 --> |YES|calculate_relay_play_time2["calculate relay play time"]
    calculate_relay_play_time2 --> calculate_ball_flight_time2["calculate ball flight time"]
    cutt_off2 --> |NO|calculate_ball_flight_time2
  end

  subgraph evaluate_grounder_play["evaluate grounder play"]
    judge_optimal_target_general3["judge optimal target general"] --> calculate_ball_flight_time3
  end

