flowchart TD
    calculate_pitched_ball --> calculate_pitch_displacement
    calculate_pitch_displacement --> evaluate_swing
    evaluate_swing --> calculate_batted_ball

    subgraph calculate_batted_ball
        direction TB
        classify_trajectory_type
        calculate_collision_spin --> combine_batted_spin --> calculate_3d_flight_path
        sample_launch_speed --> calculate_3d_flight_path
        sample_spray_angle --> calculate_3d_flight_path
        sample_launch_angle --> calculate_3d_flight_path
    end
