classDiagram
    class Player {
        +u32 id
        +Arc~str~ first_name
        +Arc~str~ last_name
        +u8 age
        +RL throw
        +Vec~DefensiveSkill~ defensive_skills
        +Option~PitcherAttribute~ pitcher_attribute
        +RL bat
        +f64 mod_ba
        +f64 mod_slg
    }

    class FullName {
        +Arc~str~ first
        +Arc~str~ last
    }

    class ItemProb~T~ {
        +T name
        +f64 prob
    }

    class PlayerAttributeProb {
        +f64 age_shape
        +f64 age_scale
        +f64 age_offset
        +f64 throw_lefty
        +f64 bat_lefty
    }

    class BatterSkillProb {
        +f64 ba_skew
        +f64 slg_skew
    }

    class DefensiveSkill {
        +Position position
        +f64 mod_uzr
    }

    class DefensiveSkillProb {
        +f64 uzr_skew
    }

    class PitcherAttribute {
        +PitcherStyle pitcher_style
        +f64 mod_velocity
        +f64 mod_control
        +f64 mod_stamina
        +f64 mod_injury_proneness
        +f64 mod_clutch
        +f64 mod_hpp
        +f64 mod_platoon_splitting
        +Vec~PitchSkill~ pitch_skills
    }

    class PitcherAttributeProb {
        +f64 velocity_skew
        +f64 control_skew
        +f64 stamina_skew
        +f64 injury_proneness_skew
        +f64 clutch_skew
        +f64 hpp_skew
        +f64 platoon_splitting_skew
    }

    class PitchSkill {
        +PitchType pitch_type
        +f64 mod_velocity
        +f64 mod_control
        +f64 mod_stamina
        +f64 mod_injury_proneness
        +f64 mod_stuff
        +f64 mod_fb
        +f64 mod_gp
        +f64 mod_horizontal_movement
        +f64 mod_vertical_movement
        +f64 mod_spin_rate
        +f64 mod_usage
    }

    class PitchSkillProb {
        +PitchType pitch_type
        +f64 velocity_skew
        +f64 control_skew
        +f64 stamina_skew
        +f64 injury_proneness_skew
        +f64 stuff_skew
        +f64 fb_skew
        +f64 gp_skew
        +f64 horizontal_movement_skew
        +f64 vertical_movement_skew
        +f64 spin_rate_skew
        +f64 usage_skew
    }

    class PlayerProb {
        +PlayerAttributeProb player_attribute_prob
        +BatterSkillProb batter_skill_prob
        +Vec~ItemProb(Position)~ position_probs
        +DefensiveSkillProb defensive_skill_prob
        +Vec~ItemProb(PitcherStyle)~ pitcher_style_probs
        +PitcherAttributeProb pitcher_attribute_prob
    }

    class League {
        +u16 id
        +Arc~str~ name
        +Vec~Team~ teams
    }

    class Team {
        +u16 id
        +Arc~str~ name
        +Vec~Player~ players
    }

    class Standing {
        +Team team
        +u16 games
        +u16 wins
        +u16 losses
        +u16 draws
        +f32 pct
        +f32 gb
        +u16 r
        +u16 ra
    }

    class GameSeason {
        +NaiveDate start_date
        +u16 season
    }

    class GameScheduler {
        +u32 id
        +u16 season
        +u16 round_seq
        +u16 seq
        +NaiveDate planned_date
        +Team away_team
        +Team home_team
        +GameType game_type
    }

    class GameHeader {
        +u32 id
        +NaiveDate actual_date
        +Team away_team
        +Team home_team
        +GameType game_type
        +u8 away_points
        +u8 home_points
    }

    class GameResult {
        +u32 id
        +NaiveDate actual_date
        +Vec~Inning~ innings
        +u8 away_points
        +u8 home_points
        +Vec~BattingOrderHistory~ batting_order_histories
    }

    class GameRow {
        +u32 id
        +u16 season
        +u16 round_seq
        +u16 seq
        +NaiveDate planned_date
        +NaiveDate actual_date
        +Team away_team
        +Team home_team
        +GameType game_type
        +Vec~Inning~ innings
        +u8 away_points
        +u8 home_points
    }

    class Inning {
        +u8 seq
        +TB tb
        +Vec~Count~ counts
    }

    class Count {
        +u8 seq
        +u8 bases_occupied
        +BattingResult result
        +u8 point
        +u8 out
    }

    class GameState {
        +u8 inning_seq
        +TB inning_tb
        +u8 away_total_point
        +u8 home_total_point
        +Lineup away_lineup
        +Lineup home_lineup
    }

    class InningState {
        +u8 count_seq
        +u8 bases_occupied
        +u8 out
    }

    class Lineup {
        +usize current_index
        +Vec~BattingOrder~ batters
    }

    class BattingOrder {
        +u8 index
        +Position position
        +Player player
    }

    class BattingOrderHistory {
        +u8 start_inning_seq
        +TB start_inning_tb
        +u8 start_count_seq
        +Option~u8~ end_inning_seq
        +Option~TB~ end_inning_tb
        +Option~u8~ end_count_seq
        +u16 team_id
        +u8 index
        +Position position
        +u32 player_id
    }

    class GameCursor {
        -Arc~GameRow~ game
        +u8 inning_seq
        +TB inning_tb
        +u8 count_seq
        +bool is_last_bottom_inning_skiped
    }

    class ScoreBoard {
        +String away_team_name
        +String home_team_name
        +u8 max_inning_num
        +u8 away_total_point
        +u8 home_total_point
        +Vec~u8~ away_innning_points
        +Vec~u8~ home_innning_points
        +bool is_last_bottom_inning_skiped
    }

    class BattingStats {
        +Player batter
        +u16 ab
        +u16 single
        +u16 double
        +u16 triple
        +u16 homerun
        +f32 ba
        +f32 rbi
    }

    class RL {
        <<enumeration>>
        Right
        Left
    }

    class PitchType {
        <<enumeration>>
        FourSeamFastball
        TwoSeamFastball
        Cutter
        Curveball
        Slider
        Sweeper
        Changeup
        Forkball
        SplitFingerFastball
        Knuckleball
    }

    class PitcherStyle {
        <<enumeration>>
        PowerPitcher
        FinessePitcher
        BalancedPitcher
    }

    class Position {
        <<enumeration>>
        P
        C
        FB
        SB
        TB
        SS
        LF
        CF
        RF
        DH
    }

    class TB {
        <<enumeration>>
        Top
        Bottom
    }

    class BattingResult {
        <<enumeration>>
        Single
        Double
        Triple
        HomeRun
        Out
    }

    class Base {
        <<enumeration>>
        First
        Second
        Third
    }

    class GameType {
        <<enumeration>>
        Exhibition
        Regular
        Postseason
    }

    class GameProgress {
        <<enumeration>>
        Ongoing
        WalkOff
        GameSet
        Postponed
    }

    class InningProgress {
        <<enumeration>>
        Ongoing
        HalfInningOver
    }

    Player --> RL : throw
    Player --> RL : bat
    Player "1" --> "0..*" DefensiveSkill : defensive_skills
    Player "1" --> "0..1" PitcherAttribute : pitcher_attribute
    DefensiveSkill --> Position : position
    PitcherAttribute --> PitcherStyle : pitcher_style
    PitcherAttribute "1" --> "0..*" PitchSkill : pitch_skills
    PitchSkill --> PitchType : pitch_type
    PitchSkillProb --> PitchType : pitch_type
    PlayerProb --> PlayerAttributeProb : player_attribute_prob
    PlayerProb --> BatterSkillProb : batter_skill_prob
    PlayerProb --> ItemProb : position_probs
    PlayerProb --> DefensiveSkillProb : defensive_skill_prob
    PlayerProb --> ItemProb : pitcher_style_probs
    PlayerProb --> PitcherAttributeProb : pitcher_attribute_prob

    League "1" --> "0..*" Team : teams
    Team "1" --> "0..*" Player : players
    Standing --> Team : team

    GameScheduler --> Team : away_team
    GameScheduler --> Team : home_team
    GameScheduler --> GameType : game_type

    GameHeader --> Team : away_team
    GameHeader --> Team : home_team
    GameHeader --> GameType : game_type

    GameResult "1" --> "0..*" Inning : innings
    GameResult "1" --> "0..*" BattingOrderHistory : batting_order_histories
    GameResult --> GameState : update_point

    GameRow --> Team : away_team
    GameRow --> Team : home_team
    GameRow --> GameType : game_type
    GameRow "1" --> "0..*" Inning : innings

    Inning --> TB : tb
    Inning "1" --> "0..*" Count : counts

    Count --> BattingResult : result

    GameState --> TB : inning_tb
    GameState --> Lineup : away_lineup
    GameState --> Lineup : home_lineup
    GameState --> GameProgress : progress
    GameState --> Inning : advance_half_inning

    InningState --> InningProgress : progress
    InningState --> BattingResult : advance
    InningState --> Count : batting_resolve

    Lineup "1" --> "1..*" BattingOrder : batters
    BattingOrder --> Position : position
    BattingOrder --> Player : player
    BattingOrderHistory --> TB : start_inning_tb
    BattingOrderHistory --> TB : end_inning_tb
    BattingOrderHistory --> Position : position

    GameCursor --> GameRow : game
    GameCursor --> TB : inning_tb
    GameCursor --> Count : current_count
    GameCursor --> ScoreBoard : current_scoreboard

    BattingStats --> Player : batter
