flowchart TD
    subgraph pitcher[Pitcher]
        calculate_release_point
        select_pitch_skill
        base_spin_angle
    end

    create_pitch --> pitcher
    calculate_pitch_displacement --> calculate_flight_time --> calculate_late_break_displacement

    